// deno run -A tools/holes.js  — writes holes.js
//
// Every part in the LDraw library that has a hole, and where those holes are. The
// command line tool reads this off the library as it goes; a browser has no
// library, so it carries the answers instead. That is the whole difference between
// the two, and this file is what closes it.
//
// It comes out around 310 kB, a fifth of that over the wire, for some 2100 parts.
// Run it again when the library is updated, or when what counts as a hole changes.
// LDraw parts are CC BY 4.0 — https://www.ldraw.org

import { colourName, describe, findLibrary, holesOf } from '../library.js';

const root = findLibrary();
if (!root) throw new Error('cannot find the LDraw library. Set LDRAWDIR.');

const holes = {}, names = {};
let scanned = 0, kept = 0, total = 0;

for (const dir of ['parts', 'UnOfficial/parts']) {
  for (const entry of Deno.readDirSync(`${root}/${dir}`)) {
    if (!entry.isFile || !entry.name.endsWith('.dat')) continue;
    scanned++;
    const key = entry.name.replace('.dat', '');
    if (holes[key]) continue;                  // official wins over unofficial
    let found;
    try { found = holesOf(root, entry.name); } catch { continue; }
    if (!found.length) continue;
    // The same place drawn twice is one hole, and it is an axle hole if any of the
    // shapes drawn there is one.
    const flat = new Map();
    for (const h of found) {
      const at = h.at.map((v) => +v.toFixed(2));
      const was = flat.get(at.join(','));
      flat.set(at.join(','), h.axle || was?.[3] ? [...at, 1] : at);
    }
    holes[key] = [...flat.values()];
    names[key] = describe(root, entry.name);
    kept++;
    total += flat.size;
  }
}

// Colour names, so a report can say "the Tan joint" and you can find it in Studio
// by looking rather than by counting.
const colours = {};
for (let code = 0; code < 600; code++) {
  const said = colourName(root, code);
  if (!/^colour /.test(said)) colours[code] = said;
}

const lines = (obj) => '{\n' + Object.entries(obj)
  .map(([k, v]) => `  "${k}": ${JSON.stringify(v)},`).join('\n') + '\n}';

Deno.writeTextFileSync('holes.js',
  `// Generated by tools/holes.js from the LDraw library. Do not edit by hand.\n` +
  `// Where every part's holes are, in LDU, in the part's own frame: [x, y, z] and\n` +
  `// a fourth 1 when an axle cannot turn in it. ${kept} parts, ${total} holes.\n\n` +
  `export const HOLES = ${lines(holes)};\n\n` +
  `export const NAMES = ${lines(names)};\n\n` +
  `export const COLOURS = ${lines(colours)};\n`);

const size = Deno.statSync('holes.js').size;
console.log(`scanned ${scanned} files, kept ${kept} parts with ${total} holes`);
console.log(`${Object.keys(colours).length} colour names, ${(size / 1024).toFixed(0)} kB written`);
