// deno run -A tools/parts.js  — writes parts.js
//
// The catalogue the web app draws and solves with. Only the part numbers are
// written down here; where their holes are comes off the LDraw library, the same
// way the command line tool reads them, so the two can never drift apart.
//
// To add a part, put its number in the list and run this again. It has to be one
// whose holes all lie in one plane and sit a stud apart along it — which is every
// straight, bent and L-shaped beam, and is what lets the app draw a part it has
// never seen as a thick round-ended line through its own holes.

import { findLibrary, describe, holesOf } from '../library.js';

const WANTED = [
  '18654', '43857', '32523', '32316', '32524', '40490', '32525', '41239', '32278',
  '32140', '32526', '32056',
  '32348', '6629', '32271',
];

const root = findLibrary();
if (!root) throw new Error('cannot find the LDraw library. Set LDRAWDIR.');

const catalogue = WANTED.map((id) => {
  const part = `${id}.dat`;
  // A hole is often drawn once per face, so the same place comes up twice. In
  // the plane there is only one hole there — and it is an axle hole if any of
  // the shapes drawn at that place is one.
  const seen = new Map();
  for (const h of holesOf(root, part)) {
    const key = `${h.at[0].toFixed(3)},${h.at[2].toFixed(3)}`;
    const was = seen.get(key);
    seen.set(key, { at: [h.at[0], h.at[2]], axle: h.axle || !!was?.axle });
  }
  const holes = [...seen.values()].sort((a, b) => a.at[0] - b.at[0] || a.at[1] - b.at[1]);
  if (!holes.length) throw new Error(`${part} has no holes`);
  return { part, what: describe(root, part).replace(/^Technic /, ''), holes };
});

const body = catalogue.map((p) =>
  `  { part: '${p.part}', what: ${JSON.stringify(p.what)}, holes: [\n` +
  p.holes.map((h) =>
    `    { at: [${+h.at[0].toFixed(4)}, ${+h.at[1].toFixed(4)}]${h.axle ? ', axle: true' : ''} },`
  ).join('\n') + '\n  ] },'
).join('\n');

Deno.writeTextFileSync('parts.js',
  `// Generated by tools/parts.js from the LDraw library. Do not edit by hand.\n` +
  `// Holes are in LDU, in the part's own frame, flattened onto the XZ plane.\n` +
  `// An axle hole is one an axle cannot turn in; the rest take a pin.\n\n` +
  `export const CATALOGUE = [\n${body}\n];\n`);

console.log(catalogue.map((p) =>
  `${p.part}  ${p.holes.length} holes, ${p.holes.filter((h) => h.axle).length} of them axle  ${p.what}`
).join('\n'));
